# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=7)),
                ('date', models.DateField()),
                ('day', models.DecimalField(decimal_places=2, max_digits=2)),
                ('low', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('open', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pips', models.DecimalField(decimal_places=4, max_digits=11)),
                ('pips_ratio', models.DecimalField(decimal_places=8, max_digits=19)),
            ],
            options={
                'db_table': 'v_day',
            },
        ),
        migrations.AlterUniqueTogether(
            name='vday',
            unique_together=set([('target', 'date')]),
        ),
    ]
